name: Backend SonarCloud Scan

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    branches:
      - main
    paths:
      - 'back/**'

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

   
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

     
      - name: Run SonarCloud analysis
        run: |
          cd back
          mvn sonar:sonar \
            -Dsonar.token=${{ env.SONAR_TOKEN }} \
            -Dsonar.projectKey=tangilc_OC-P10_CICD:back \
            -Dsonar.organization=tangilc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.java.coveragePlugin=jacoco
