name: Backend Build & Coverage

on:
   push:
    branches: [ main,TestDev ]
    paths:
      - 'back/**'
   pull_request:
    branches:
      - main
    paths:
      - 'back/**'

jobs:
  build-and-report:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

 
      - name: Build and run tests
        run: |
          cd back
          mvn clean verify

     
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: back/target/surefire-reports/*.xml

     
      - name: Archive coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend-coverage-report.xml
