name: Backend SonarCloud Scan

on:
push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    branches:
      - main
    paths:
      - 'back/**'

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

   
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

     
      - name: Run SonarCloud analysis
        run: |
          cd back
           mvn clean compile sonar:sonar \
            -Dsonar.token=${{ env.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=EvoSix_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-main
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.exclusions=node_modules/**,test/**
             -Dsonar.java.binaries=target/classes
