name: Frontend Build & Coverage

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

 
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

     
      - name: Install Front-end dependencies
        working-directory: front
        run: npm ci

   
      - name: Install Chrome browser for tests
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

   
      - name: Run Front-end tests with coverage
        working-directory: front
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          npm test -- --browsers ChromeHeadless --watch=false --code-coverage --karma-config=karma.conf.js


      - name: Frontend Test Report
        if: always()
        uses: phoenix-actions/test-reporting@v14
        with:
          name: Frontend Tests
          path: front/coverage/bobapp/test-results.xml
          reporter: java-junit

   
      - name: Upload front-end coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/bobapp
